# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c971fc957f3c9287b0b501038ec89593ae5fbdf54ecdc998ea19f673be467f70fbe4cacffde8b2df521f3666c4a380bbbbf9e5957a6ac501231bddaf4ecd00af

test:
  secret_key_base: 83c3f67734900b51a7f79c860be568be7178c6a50f9b44b8a6c4043a737c6d01492ba7a2195cf191a9deb5fc5f860f70a5a51099834d484926fc20a5fbe710a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
